from fastapi import APIRouter, HTTPException, Response
from typing import List, Optional
from sqlmodel import Session, select
from app.models.player import Player
from app.models.negotiation import Negotiation
from app.core.db import engine
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
import io
from datetime import datetime

router = APIRouter(prefix="/reports", tags=["reports"])

@router.get("/player/{player_id}/pdf")
async def get_player_report_pdf(player_id: str):
    with Session(engine) as session:
        player = session.get(Player, player_id)
        if not player:
            raise HTTPException(status_code=404, detail="Player not found")
        
        # Determine active negotiation
        neg = session.exec(select(Negotiation).where(Negotiation.player_id == player_id)).first()

        buffer = io.BytesIO()
        p = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4

        # Premium Branding
        p.setFillColor(colors.hexColor("#00F2FF")) # Primary Brand Color
        p.rect(0, height - 100, width, 100, fill=1)
        
        p.setFillColor(colors.black)
        p.setFont("Helvetica-Bold", 32)
        p.drawString(40, height - 60, "SCIENCEBALL.AI")
        
        p.setFont("Helvetica-Bold", 14)
        p.drawString(40, height - 85, "CONFIDENTIAL TACTICAL DOSSIER")

        # Player Info
        p.setFillColor(colors.black)
        p.setFont("Helvetica-Bold", 24)
        p.drawString(40, height - 150, player.name.upper())
        
        p.setFont("Helvetica", 12)
        p.drawString(40, height - 175, f"CLUB: {player.club} | NATIONALITY: {player.nationality}")
        p.drawString(40, height - 195, f"AGE: {player.age} | POSITION: {player.position} | VALUE: €{player.market_value:,.0f}")

        # Tactical Summary
        p.setStrokeColor(colors.lightgrey)
        p.line(40, height - 220, width - 40, height - 220)
        
        p.setFont("Helvetica-Bold", 14)
        p.drawString(40, height - 250, "TACTICAL INTELLIGENCE SUMMARY")
        
        p.setFont("Helvetica", 10)
        text_object = p.beginText(40, height - 275)
        text_object.setFont("Helvetica", 10)
        text_object.textLines(player.scientific_dossier or "No technical dossier available for this profile.")
        p.drawText(text_object)

        # Financial Status
        if neg:
            p.setFont("Helvetica-Bold", 14)
            p.drawString(40, height - 450, "FINANCIAL DISCLOSURE")
            p.setFont("Helvetica", 11)
            p.drawString(40, height - 475, f"CURRENT STATUS: {neg.status}")
            p.drawString(40, height - 495, f"ESTIMATED FEE: €{neg.estimated_fee:,.0f}")
            p.drawString(40, height - 515, f"CONTRACT DURATION: {neg.contract_years} YEARS")

        # Footer
        p.setFont("Helvetica-Oblique", 8)
        p.drawString(40, 40, f"Generated by ScienceBall Intel Engine | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

        p.showPage()
        p.save()

        buffer.seek(0)
        return Response(content=buffer.getvalue(), media_type="application/pdf", 
                        headers={"Content-Disposition": f"attachment; filename=SB_Dossier_{player_id}.pdf"})

@router.get("/risk-assessment/{player_id}")
async def get_risk_assessment(player_id: str):
    with Session(engine) as session:
        player = session.get(Player, player_id)
        if not player:
            raise HTTPException(status_code=404, detail="Player not found")
        
        # Robust risk logic
        medical_risk = 10
        if player.medical_dna:
            risk_label = player.medical_dna.get("injury_risk", "Low")
            medical_risk = 40 if risk_label == "High" else (25 if risk_label == "Medium" else 10)
        
        market_volatility = 20
        tactical_risk = 15 # Based on SystemFitAI logic
        
        total_risk = medical_risk + market_volatility + tactical_risk
        
        return {
            "player_id": player_id,
            "overall_score": total_risk,
            "medical": medical_risk,
            "market": market_volatility,
            "tactical": tactical_risk,
            "level": "HIGH" if total_risk > 60 else ("MEDIUM" if total_risk > 30 else "LOW")
        }
